on: push
jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build
  run:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Kill any running instances
        run: |
          pkill -f ./our-home-server || echo "No existing process found"
      - name: Run
        run: nohup ./our-home-server & echo "Server restarted successfully"
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
