on: push
jobs:
  build-and-run:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v5
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build
      - name: Run
        run: ./our-home-server
        env:
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
